name: BukkitFeatures
version: '${project.version}'
api-version: 1.18
main: de.joshiworld.bukkit.main.Paper
depend:
  - LuckPerms
  - Citizens
commands:
  sethome:
    description: set a new home Location
    usage: /sethome <Homename>
  setwarp:
    permission: bungeefeatures.warp
    description: set a new warp Location
    usage: /setwarp <warpname>
  setportal:
    permission: bungeefeatures.portal
    description: set a new warp Location
    usage: /setportal <NPCName> <Server>
