name: BukkitFeatures
version: '${project.version}'
api-version: 1.18
main: de.joshiworld.bukkit.Paper
depend:
  - LuckPerms
commands:
  sethome:
    description: set a new home Location
    usage: /sethome <Homename>
  setwarp:
    description: set a new warp Location
    usage: /setwarp <warpname>